### ISSUE TITLE
[Bug]cusor deviate when scale modefied by `document.body.style.zoom`

### ISSUE THREAD

**Issue by serfend** [apache/incubator-echarts#12645]
### Version
4.7.0

### Reproduction link
[https://serfend.gitee.io/#/dashboard](https://serfend.gitee.io/#/dashboard)

### Steps to reproduce
document.body.style.zoom = 1.25;

### What is expected?
cusor should act at events position where it exactly is.

### What is actually happening?
deviate about 25% on the right

**Comment by plainheart** [comment]
It seems to be a bug, but css zoom is a non-standard method and [many browsers have a very poor compatibility for css zoom](https://caniuse.com/#feat=css-zoom) (especially in Firefox). Is it necessary to fix?
Instead, we can use `document.body.style.transform = 'scale(1.25)'` to resolve this requirement, which is working well.([Can I Use: CSS Transform](https://caniuse.com/#search=transform))
For IE or other browsers compatibilities, we can add browser prefix for it.
```js
document.body.style.webkitTransform = 'scale(1.25)';
document.body.style.MozTransform = 'scale(1.25)';
document.body.style.OTransform = 'scale(1.25)';
document.body.style.msTransform = 'scale(1.25)';
document.body.style.transform = 'scale(1.25)';
```
or just add a class for `body`
```css
body {
  -ms-transform: scale(1.25);          /* IE 9 */
  -moz-transform: scale(1.25);         /* Firefox */
  -webkit-transform: scale(1.25);      /* Safari & Chrome */
  -o-transform: scale(1.25);           /* Opera */
  transform: scale(1.25);
}
```
