### ISSUE TITLE
同时设置css 和 行内样式时, tooltip 样式错误

### ISSUE THREAD

**Issue by wp56610** [apache/incubator-echarts#12994]
### Version
4.8.0

### Reproduction link
[https://codepen.io/wp56610/pen/rNxoNJo](https://codepen.io/wp56610/pen/rNxoNJo)

### Steps to reproduce
system: Windows NT 10.0; Win64; x64
Browser: chrome 83.0.4103.116  /  Firefox/75.0

### What is expected?
tooltip should be shirnk 

### What is actually happening?
tooltip is too big more than expected

**Comment by plainheart** [comment]
你的 CSS 代码作用范围太大，这会影响 tooltip 的 div 容器样式。
```css
div{
    display: inline-block;
    width: 600px;
    height: 400px
}
```
将 div 标签选择器改为对应的 id 选择器 `#stackArea` 就不会出现这个问题了。
